language: "en-US"
early_access: false
reviews:
  request_changes_workflow: true  # Enable Request Changes Workflow
  high_level_summary: true
  poem: true
  review_status: true
  issue_validation: true
  code_review_feedback: true
  collapse_walkthrough: false
auto_review:
  enabled: true
  ignore_title_keywords:
    - "WIP"
    - "DO NOT MERGE"
  drafts: false
chat:
  auto_reply: true
