name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Log Workflow Start
        run: echo "Starting code review workflow"      

      - name: Log GITHUB TOKEN KEY
      
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}"
      - name: Log OPENAI API KEY
        run: |
          echo "OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}"
        
      - name: Verify Pull Request Number
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"

      - name: Run Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: English
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-3.5-turbo
          PROMPT: |
            Please review the following code changes carefully and provide your feedback:

            ```diff
            @@ -1,5 +1,5 @@
            - int x = 5;
            - int y = 10;
            + int a = 3;
            + int b = 8;
            ```
            After reviewing, please leave your comments and suggestions for improvement.

            - Is the variable naming consistent?
            - Are there any potential logic errors?
            - Any suggestions for optimization?
          top_p: 1
          temperature: 1
          max_tokens: 4096
          MAX_PATCH_LENGTH: 10000      
      - name: Log Workflow End
        run: echo "Code review workflow completed"
